version: '3' 
services: 

    db:
      image: postgres
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: example
      container_name: db_backend
    backend:  
      image: backend
      environment:
        - FRONT_URL=*
        - DB_USERNAME=postgres
        - DB_PASSWORD=example
        - DB_HOST=db
      ports: 
        - 8000:8000